apiVersion: v1
kind: Service
metadata:
  name: geonode-postgis
  labels:
    app: geonode-postgis
spec:
  type: LoadBalancer
  ports:
  - name: geonode-postgis-port
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: geonode-postgis