apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    run: rabbitmq
spec:
  type: ClusterIP
  selector:
    run: rabbitmq
  ports:
  - name: messageque
    port: 5672
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/geonode/rabbitmq/data"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: geonode
      run: rabbitmq
  serviceName: "rabbitmq"
  replicas: 1
  template:
    metadata:
      labels:
        app: geonode
        run: rabbitmq
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - image: rabbitmq:3.7-alpine
        name: rabbitmq
        ports:
        - containerPort: 5672
        volumeMounts:
        - name: rabbitmq-data-storage
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:  
  - metadata:
      name: rabbitmq-data-storage
    spec:
      volumeName: pv-rabbitmq-data
      storageClassName: local-storage
      resources:
        requests:
          storage: 2Gi
      accessModes:
        - ReadWriteMany

