apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/geonode/rabbitmq/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-rabbitmq-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi