apiVersion: apps/v1
kind: Deployment
metadata:
  name: geonode-postgis
  labels:
    app: postgis
spec:
  selector:
    matchLabels:
      app: postgis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgis
    spec:
      volumes:
      - name: postgis-dbbackups-storage
        persistentVolumeClaim:
          claimName: claim-postgis-dbbackups
      - name: postgis-dbdata-storage
        persistentVolumeClaim:
          claimName: claim-postgis-dbdata
      containers:
      - image: geonode/postgis:13
        name: postgis
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geonode-postgis
              key: postgres-password
        - name: GEONODE_DATABASE
          value: geonode
        - name: GEONODE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geonode-postgis
              key: geonode-database-password
        - name: GEONODE_DATABASE_SCHEMA
          value: public
        - name: GEONODE_GEODATABASE_SCHEMA
          value: public         
        ports:
        - containerPort: 5432
          name: postgis
        volumeMounts:
        - name: postgis-dbdata-storage
          mountPath: /var/lib/postgresql/data
        - name: postgis-dbbackups-storage
          mountPath: /pg_backups

