apiVersion: apps/v1
kind: Deployment
metadata:
  name: geonode-postgis
  labels:
    app: postgis
spec:
  selector:
    matchLabels:
      app: postgis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgis
    spec:
      initContainers:
      - image: busybox:1.28
        name: waiting-for-volumes
        command: ['sh', '-c', "sleep 10"]
      containers:
      - image: geonode/postgis:13
        name: postgis
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        # - name: POSTGRES_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: geonode-postgis
        #       key: postgres-user
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: geonode-postgis
        #       key: postgres-password
        - name: GEONODE_DATABASE
          valueFrom:
            secretKeyRef:
              name: geonode-postgis
              key: database
        - name: GEONODE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geonode-postgis
              key: database-password
        - name: GEONODE_GEODATABASE
          valueFrom:
            secretKeyRef:
              name: geonode-postgis
              key: geodatabase
        - name: GEONODE_GEODATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geonode-postgis
              key:  geodatabase-password
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: postgis-dbdata-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        - name: postgis-dbbackups-storage
          mountPath: /pg_backups
      volumes:
      - name: postgis-dbbackups-storage
        persistentVolumeClaim:
          claimName: claim-postgis-dbbackups
      - name: postgis-dbdata-storage
        persistentVolumeClaim:
          claimName: claim-postgis-dbdata