apiVersion: v1
kind: Service
metadata:
  name: postgis
  labels:
    app: postgis
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgis