---
apiVersion: v1
kind: Service
metadata:
  name: postgis
  labels:
    app: postgis
spec:
  selector:
    app: postgis
    tier: backend
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432