
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgis-dbdata
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/geonode/postgis/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgis-dbbackups
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/geonode/postgis/pg_backups"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  claim-postgis-dbbackups
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-postgis-dbdata
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi