apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: geonode-postgis-cluster
  #namespace: default
spec:
  teamId: "geonode"
  volume:
    size: 3Gi
  numberOfInstances: 1
  users:
    geonode:
    - superuser
    - createdb
    - login
    geogeonode:
    - superuser
    - createdb
    - login
  databases:
    geonode: geonode
    geogeonode: geogeonode
  preparedDatabases:
    geogeonode:
      # schemas:
      #   public: {}
      extensions:
        pg_partman: public
        postgis: public
    geonode:
      # schemas:
      #   public: {}
      extensions:
        pg_partman: public
        postgis: public
  postgresql:
    version: "13"

