apiVersion: apps/v1
kind: Deployment
metadata:
  name: geonode-django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
    spec:
      hostname: django
      volumes:
      - name: geoserver-static-storage
        persistentVolumeClaim:
          claimName: claim-shared-static
      - name: geoserver-data-dir-storage
        persistentVolumeClaim:
          claimName: claim-shared-data-dir
      - name: geoserver-data-storage
        persistentVolumeClaim:
          claimName: claim-shared-data
      - name: geoserver-backup-restore-storage
        persistentVolumeClaim:
          claimName: claim-shared-backup-restore
      - name: geoserver-tmp-storage
        persistentVolumeClaim:
          claimName: claim-shared-tmp
      containers:
      - image: mwall2bitflow/geonode:3.1.1
        name: genode-django
        args: ["/usr/src/geonode/entrypoint.sh","uwsgi", "--ini", "/usr/src/geonode/uwsgi.ini"]
        env:
        # GEOSERVER SECRETS
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: geoserver-login
              key: admin_user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geoserver-login
              key: admin_password
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: geoserver-login
              key: admin_emailaddr
        # POSTGIS SECRETS
        - name: GEONODE_DATABASE
          valueFrom:
            secretKeyRef:
              name: geonode-postgis
              key: database
        - name: GEONODE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geonode-postgis
              key: database-password 
        # Other ENV
        - name: IS_CELERY
          value: "False"
        envFrom:
        - configMapRef:
            name: django-config
        - configMapRef:
            name: geoserver-config
        - configMapRef:
            name: nginx-config
        - configMapRef:
            name: postgis-config
        - configMapRef:
            name: rabbitmq-config        
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: geoserver-static-storage
          mountPath: /mnt/volumes/statics
        - name: geoserver-data-dir-storage
          mountPath: /geoserver_data/data
        - name: geoserver-backup-restore-storage
          mountPath: /backup_restore
        - name: geoserver-data-storage
          mountPath: /data
        - name: geoserver-tmp-storage
          mountPath: /tmp