apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  type: ClusterIP
  ports:
  - name: uwsgi
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: django