apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    app: geonode
  type: ClusterIP
  ports:
    - name: http-alt
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: http-alt2
      protocol: TCP
      port: 8001
      targetPort: 8001