apiVersion: v1
kind: Secret
metadata:
  name: geoserver-oauth
data:
  apiKey: "" 
  clientId: Jrchz2oPY3akmzndmgUTYrs9gczlgoV20YPSvqaV 
  clientSecret: rCnp5txobUo83EpQEblM8fVj3QT5zb5qRfxNsuPzCqZaiRyIoxM4jdgMiZKFfePBHYXCLd7B8NlkfDBY9HKeIQPcy5Cp08KQNpRHQbjpLItDHv12GvkSeXp6OxaUETv3 

# ---  
# apiVersion: v1
# kind: Secret
# metadata:
#   name: geoserver-login
# type: Opaque
# data:
#   admin_user: YWRtaW4K # admin
#   admin_password: Z2Vvc2VydmVyCg== # geoserver
# #GEOSERVER_ADMIN_USER=admin
# #GEOSERVER_ADMIN_PASSWORD=geoserver