apiVersion: v1
kind: Service
metadata:
  name: geoserver
  labels:
    run: geoserver
spec:
  selector:
    run: geoserver
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
