apiVersion: v1
kind: Service
metadata:
  name: postgis
  labels:
    app: postgis
spec:
  type: ClusterIP
  ports:
  - name: geoserver
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: postgis