apiVersion: v1
kind: Service
metadata:
  name: geoserver
  labels:
    app: geoserver
spec:
  selector:
    app: geonode
  type: ClusterIP
  ports:
  - name: geoserver
    port: 8080
    protocol: TCP
    targetPort: 8080
