apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  GEONODE_LB_HOST_IP: nginx
  GEONODE_LB_PORT: "80"
  # IP or domain name and port where the server can be reached on HTTPS (leave HOST empty if you want to use HTTP only)
  # port where the server can be reached on HTTPS
  HTTP_HOST: nginx
  HTTPS_HOST: nginx
  HTTP_PORT: "80"
  HTTPS_PORT: "443"
  # Let's Encrypt certificates for https encryption. You must have a domain name as HTTPS_HOST (doesn't work
  # with an ip) and it must be reachable from the outside. This can be one of the following :
  # disabled : we do not get a certificate at all (a placeholder certificate will be used)
  # staging : we get staging certificates (are invalid, but allow to test the process completely and have much higher limit rates)
  # production : we get a normal certificate (default)
  LETSENCRYPT_MODE: disabled
  # LETSENCRYPT_MODE: staging
  # LETSENCRYPT_MODE: production
  RESOLVER: 127.0.0.11