
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geonode-nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostname: nginx
      volumes:
      - name: nginx-confd-storage
        persistentVolumeClaim:
          claimName: claim-nginx-confd
      - name: nginx-certifcate-storage
        persistentVolumeClaim:
          claimName: claim-nginx-certificates
      - name: geonode-static-storage
        persistentVolumeClaim:
          claimName: claim-shared-static
      initContainers:
      - image: geonode/nginx:latest
        name: geonode-ngninx-init-conf-directory
        volumeMounts:
        - name: nginx-confd-storage
          mountPath: /mnt/nginx/     
        command: [sh, -exc]
        args:
          - |
            cp -rn /etc/nginx/* /mnt/nginx/
            true
      containers:
      - image: geonode/nginx:latest
        name: nginx
        envFrom:
        - configMapRef:
            name: nginx-config
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-confd-storage
          mountPath: /etc/nginx
        - name: nginx-certifcate-storage
          mountPath: /geonode-certificates
        - name: geonode-static-storage
          mountPath: /mnt/volumes/statics

