
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-confd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/geonode/nginx/confd"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-certificates
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/geonode/nginx/certificates"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  claim-nginx-certificates
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nginx-confd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi